spring.application.name=analyser
logging.level.com.nse.analyser=DEBUG

spring.datasource.url=jdbc:clickhouse://localhost:8123
spring.datasource.username=username
spring.datasource.password=userpassword
spring.datasource.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver
